# See 'bookworm' for stable Debian version names
FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.11-bookworm

# The 'devcontainer.json' will run 'pip install' for us.
# We can add any other OS-level packages here.
# For example:
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
# COPY ../requirements.txt /tmp/pip-tmp/
# RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#    && rm -rf /tmp/pip-tmp
